language: python
dist: xenial
cache: pip
matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.7'
      env: TOXENV=sphinx1.8
    - python: '3.7'
      env: TOXENV=blockdiag_dev
    - python: '3.7'
      env: TOXENV=coverage
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U docutils pip setuptools tox
script: tox
